[sampleService]
id = "5e72ca9eda3a9a154d25e6b3"
key = "mW7r59SHlVo5VtK+ZZpqY+SAkf1U3YeuZwQbIT2yNcvPpi15tAKjEehl2TZPteSmK4wx90NRgvFZKyMcML8TgIGVKcWhz/cGtAj/C4L190lPTqjT+G5IH2QMJxL/ojyB0PWS1gzhxaBl49wMgDfrKy/dZoz2XEHfJqQKUJYzBME="